apiVersion: v1
kind: ConfigMap
metadata:
 name: ready-up
data:
 bootstrap.properties: |
  vault.pki.enabled: false
  spring.application.name: ready-up
  spring.cloud.vault.enabled: false
  spring.cloud.vault.host: vault.vault.svc.cluster.local
  spring.cloud.vault.port: 8200
  spring.cloud.vault.scheme: http
  spring.cloud.vault.authentication: TOKEN
  spring.cloud.vault.generic.enabled: false
  spring.cloud.vault.kv.enabled: false
  spring.cloud.vault.kv.backend: ready-up
  spring.cloud.vault.token: {{ .Values.ready_up.vaultToken }}