# Using this together with nginx-ingress installed as described here - https://kubernetes.github.io/ingress-nginx/deploy/#generic-deployment

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ready-up-ingress
    annotations:
        kubernetes.io/tls-acme: 'true'
        ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-modsecurity: "true"
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
spec:
  rules:
    - host: ready-up.nathanrahm.com
      http:
        paths:
         - path: /
           backend:
             service:
               name: ready-up
               port: 
                 name: http
         - path: /actuator
           backend:
             service:
               name: nowhere
               port:
                 name: http
  tls:
        - hosts:
              - ready-up.nathanrahm.com
          secretName: ready-up-tls
